### ISSUE TITLE
bug: Error message should explain that issue is invalid

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/MapLight#58]
Error message implies that there is a problem with the app, instead of there being a problem with the issue that was entered. This is a **User Error**:

1. User who filled out the issue
OR
2. User who entered an invalid issue into the app

**planetarium url**: https://maplight.vercel.app/roadmap/github.com/pln-planning-tools/MapLight/issues/36
**issue**: https://github.com/pln-planning-tools/MapLight/issues/36
**App error message**: Application error: a client-side exception has occurred (see the browser console for more information).

### App screenshot
<img width="827" alt="image" src="https://user-images.githubusercontent.com/1173416/197982490-41ef848b-6b94-4411-81c9-4babf9d64c72.png">

### Browser console screenshot
<img width="864" alt="image" src="https://user-images.githubusercontent.com/1173416/197982044-12e9e2f6-7029-4158-acf6-49395259bea5.png">

**Comment by AlexxNica** [comment]
Thanks @SgtPooki!
